apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denyherocreatethreathandler
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: denyherocreatethreatrequest
spec:
  compiledTemplate: checknothing
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyherocreatethreat
spec:
  match: destination.labels["app"] == "threats" && source.labels["app"]=="heroes" && source.labels["version"] == "v3"
  actions:
    - handler: denyherocreatethreathandler
      instances: [denyherocreatethreatrequest]
