apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: heroes-vtl-svc
spec:
  hosts:
    - "*"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /hero-service/
      rewrite:
        uri: /
      route:
        - destination:
            host: heroes
            subset: v2
            port:
              number: 3000
