# Heroes v2 deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-v2
  labels:
    app: heroes
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
      version: v2
  template:
    metadata:
      labels:
        app: heroes
        version: v2
    spec:
      containers:
        - name: heroes
          image: hero-service:v2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: heroes
spec:
  host: heroes
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
